# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arena.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'arena.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rena.proto\x12\x05\x61rena\"\"\n\x10SubscribeRequest\x12\x0e\n\x06worker\x18\x01 \x01(\t\"\x81\x01\n\x07\x43ommand\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x12\n\nsubmission\x18\x03 \x01(\t\x12\x15\n\rsubmission_id\x18\x04 \x01(\t\x12\x0e\n\x06target\x18\x05 \x01(\t\x12\x0c\n\x04\x62ots\x18\x06 \x01(\x05\x12\x10\n\x08\x64uration\x18\x07 \x01(\x05\"1\n\x08RunEvent\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x15\n\rsubmission_id\x18\x02 \x01(\t\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32l\n\x07\x43ontrol\x12\x36\n\tSubscribe\x12\x17.arena.SubscribeRequest\x1a\x0e.arena.Command0\x01\x12)\n\nReportDone\x12\x0f.arena.RunEvent\x1a\n.arena.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arena_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=22
  _globals['_SUBSCRIBEREQUEST']._serialized_end=56
  _globals['_COMMAND']._serialized_start=59
  _globals['_COMMAND']._serialized_end=188
  _globals['_RUNEVENT']._serialized_start=190
  _globals['_RUNEVENT']._serialized_end=239
  _globals['_ACK']._serialized_start=241
  _globals['_ACK']._serialized_end=258
  _globals['_CONTROL']._serialized_start=260
  _globals['_CONTROL']._serialized_end=368
# @@protoc_insertion_point(module_scope)
